
POST {{content_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "",
  "publishStatus": ""
}

### 删除课程计划
DELETE {{content_host}}/content/teachplan/237


### 测试helloworld
GET {{content_host}}/content/hello

### 测试category
GET {{content_host}}/content/course-category/tree-nodes

### 测试categoryWithCount
GET {{content_host}}/content/course/categoryWithCount

### 课程增长率
GET {{content_host}}/content/course/compareWithLastYear

### 课程发布量增长率
GET {{content_host}}/content/publish/compareWithLastYear

### 教师人数增长率/年
GET {{content_host}}/content/teacher/compareWithLastYear
